### ISSUE TITLE
hf2がpanicする

### ISSUE THREAD

**Issue by sinyo-matu** [tomoyuki-nakabayashi/Embedded-Rust-from-Basics#12]
私の環境の問題かもしれませんが、プログラムをWio-Terninalに書き込もうとすると、hf2がpanicする
```shell
Compiling wio-examples v0.1.0 (/Users/user/Developer/Rust/wio_examples)
    Finished dev [unoptimized + debuginfo] target(s) in 10.52s
    Searching for a connected device with known vid/pid pair.
    Trying  Ok(Some("Seeed Studio")) Ok(Some("Wio Terminal"))
    Flashing "/Users/user/Developer/Rust/wio_examples/target/thumbv7em-none-eabihf/debug/examples/6-2-led_and_button"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Communication', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-hf2-0.3.1/src/main.rs:118:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
hf2の方にもissue出しました。
https://github.com/jacobrosenthal/hf2-rs/issues/38

**Comment by tomoyuki-nakabayashi** [comment]
ご報告ありがとうございます。
知っている限りでは2件目ですので、調査してみます。

**Comment by haryu703** [comment]
私の環境でもUSB 2,0ポートでは同じ現象が発生していましたが、USB 3.0ポートを使うと発生しなくなりました。
すべてのポートで検証したわけではないのでこれも環境次第かもしれませんが…。

**Comment by sinyo-matu** [comment]
> 私の環境でもUSB 2,0ポートでは同じ現象が発生していましたが、USB 3.0ポートを使うと発生しなくなりました。
> すべてのポートで検証したわけではないのでこれも環境次第かもしれませんが…。

私の場合、USB 3.1 type-c -> USB 3.1 のハブを使っています。

**Comment by ryoha000** [comment]
僕も同じ現象が起こりましたが 3.0のポートから2.0のポートに変えたらエラーが出なくなりました

**Comment by sinyo-matu** [comment]
hf2 v0.3.3にアップロードしたからなのかわかりましせんが、panicしなくなりました。
クローズしますね。
ありがとうございました！
