### ISSUE TITLE
些細な記載ミス(p.283)

### ISSUE THREAD

**Issue by zinziroge** [tomoyuki-nakabayashi/Embedded-Rust-from-Basics#14]
些細な記載ミスです
p.283
誤) $ cargo hf2 --example hello_lcd
正) $ cargo hf2 --example 7-4-hello_lcd

**Comment by zinziroge** [comment]
p.284も同様です。
誤) $ cargo hf2 --example hello_lcd --release
正) $ cargo hf2 --example 7-4-hello_lcd --release

**Comment by tomoyuki-nakabayashi** [comment]
ありがとうございます。
正誤表に追記します。
