### ISSUE TITLE
些細なtypo

### ISSUE THREAD

**Issue by ykomatsu** [tomoyuki-nakabayashi/Embedded-Rust-from-Basics#15]
度々すみません。
読むのに全然支障はないのですが、増刷のときとかに直っていると嬉しいです。

P.208の本文：

```
Rustの安全性の補償範囲外であるためunsafeな処理です。
```

`補償範囲外` → `保証範囲外`

P.209のソースコード中：

```
カウントダウンタイマを現すトレイト
```

`現す` → `表す`

P.214の本文：

```
Wio Terminalファームウェアを書き込むと
```

`Wio Terminalファームウェアを` → `Wio Terminalにファームウェアを`

P.224の本文：

```
マイコンにはADCが内蔵されているもの多く
```

`内蔵されているもの多く` → `内蔵されているものが多く`

P.226のソースコード中：

```
PD1をACD入力として初期化し
```

`ACD` → `ADC`

P.232の本文：

```
I2Cはクロック信号で同期を行う同期式のリアル通信方式です。
```

`リアル通信方式` → `シリアル通信方式`

**Comment by tomoyuki-nakabayashi** [comment]
大変助かります。ありがとうございます。
正誤表に記載を追加します。
