### ISSUE TITLE
p.166 define_pins!の説明について質問です

### ISSUE THREAD

**Issue by uchan-nos** [tomoyuki-nakabayashi/Embedded-Rust-from-Basics#18]
p.166の第1段落で
> しかし、P.132のコードではsplit()メソッドを使用せず、atsamd-halクレートが用意しているより便利なAPIを利用しています。

とあります。
「便利なAPI」とは `support::init()` のことでしょうか？
だとすると、p.166で紹介されている `define_pins!` との関連性がよく分かりませんでした……
`support::init()` が内部で `define_pins!` を利用している、ということなのでしょうか？

もしかして、p.132ではなくp.165の一番上に書いてあるコード辺のことを指しているのであれば、
確かにsplit()を使用せず、（define_pins!により定義した？）Pins構造体を使っており、説明が符合すると感じますが。

**Comment by tomoyuki-nakabayashi** [comment]
wio_terminal crate で用意されている `Pins` 構造体および `Pins::new()` などの関数/メソッドを意図していました。

`split()` を直接使う場合、`pins.pa15` のようにハードウェアのピンを意識した名前で使わないといけないですが、`Pins` 構造体を通すと、`pins.user_led` のようなより直感的な名前で使えるようになっています。

**Comment by uchan-nos** [comment]
分かりました。ありがとうございます。
