### ISSUE TITLE
Input<Floating>な値に対してinto_floating_input()を呼ぶ必要性

### ISSUE THREAD

**Issue by uchan-nos** [tomoyuki-nakabayashi/Embedded-Rust-from-Basics#19]
`wio::Pins::new()` により生成した各ピンは、デフォルトで `Input<Floating>` という型なのですよね。

例えば p.170 で、改めて `pins.button1.into_floating_input(&mut pins.port)` のように
`into_floating_input()` を呼んでいるのはなぜなのでしょうか？

試しに `into_floating_input()` を呼ばず、 `let button1 = pins.button1;` などと書くと
コンパイルできますがボタン入力が読めませんでしたので、何か差があるとは思うのですが。

**Comment by tomoyuki-nakabayashi** [comment]
気づいてしまいましたか…。

実は、初期状態では GPIO の入力バッファが無効になっており、フローティング入力かつ入力が無効な状態になっています。
`into_floating_input()` を呼び出すと入力バッファが有効になるので、一度明示的にモードを変えないといけないようになっています (書籍に書こうかどうか迷って最終的に載らなかった内容です) 。

個人的には、初期状態では `Pin<Uninitialized>` みたいになっていると良いと思うのですが…。

**Comment by uchan-nos** [comment]
回答ありがとうございます。

確かに最初は何も使えない型になってて欲しいですよね。
なぜそのような設計になっているか謎は残りますが、疑問は解決したのでクローズします。
