### ISSUE TITLE
ポートに 8 ビット値を出力する方法

### ISSUE THREAD

**Issue by uchan-nos** [tomoyuki-nakabayashi/Embedded-Rust-from-Basics#20]
本書では GPIO をピン単位で読み書きする方法（split() する方法）は紹介されているのですが、
バイト単位（あるいは 32 ビット単位でも可）で読み書きする方法を知りたいです。

なぜかというと、PB0～PB7 に同じタイミングで信号を出したいからです。

試しに、PB0～PB3 の各ピンを順に `set_high()` し、その後 `set_low()` することを繰り返すプログラムを書いてみました。
こんな感じです。

```
loop {
    pb0.set_high().unwrap();
    pb1.set_high().unwrap();
    pb2.set_high().unwrap();
    pb3.set_high().unwrap();
    pb0.set_low().unwrap();
    pb1.set_low().unwrap();
    pb2.set_low().unwrap();
    pb3.set_low().unwrap();
}
```

各ピンの波形を観察すると、PB0～PB3 の信号は一斉にではなく、順に変化することが分かりました。
`cargo build --release` でリリースビルドしたので、もしかしたら最適化されないかなと思いましたが、ダメでした。

![IMG_20210621_174258](https://user-images.githubusercontent.com/1825663/122739782-451bc880-d2be-11eb-9429-a2c662fd2e46.jpg)

オシロスコープの仕様で、4 つのグリッドに上から順にプローブ 1、3、2、4 が表示されています。
上から PB0、1、2、3 と並ぶように Wio Terminal とプローブを接続しています。

**Comment by tomoyuki-nakabayashi** [comment]
回答遅くなりました。
embedded-hal を使った範囲では、できないと思います。
もう1つレイヤーを下げて、PAC の API でGPIO ポートのレジスタを直接制御すると、同一ポートの GPIO ピンであれば同時に制御可能かと思います。
（こちらで検証できていないですが…）

**Comment by uchan-nos** [comment]
回答ありがとうございます。通知設定してなくて気付かず遅くなりました。

embedded-hal ではできなさそうとのこと、承知しました。

PAC というヒントを元にちょっと探してみたところ、
https://github.com/atsamd-rs/atsamd/tree/master/pac/atsamd51p/src/port/group
この辺で定義されてる dirset や outset などを使うと何かできそうな気がしました。
（この dirset や outset は CPU のレジスタに直アクセスできそうな感じがする）

後は自分でなんとかやってみます。また詰まったらお邪魔させていただきますね。
