### ISSUE TITLE
P133でのエラーについて

### ISSUE THREAD

**Issue by Akud4m4** [tomoyuki-nakabayashi/Embedded-Rust-from-Basics#21]
P133のLチカを書いてみるで、コードを書き込んだのちcargo runをしようとしたのですが以下のエラーが出てしまいました。
何が問題でしょうか。よろしくお願いします。

error: failed to parse manifest at `C:\Users\ユーザー名\my-blink\Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  invalid escape character in string: `c` at line 2 column 29

**Comment by ciniml** [comment]
エラーメッセージからするとCargo.tomlにエラーがあるようです。該当のCargo.tomlを本issueにアップロードしていただけますか？

**Comment by Akud4m4** [comment]
こちらになります
[package]
authors = ["DESKTOP-I4FGR4R\choko<メールアドレス>"]
name = "my-blink"
edition = "2018"
version = "0.1.0"

[dependencies]
support = { path = "support" }
panic-halt = "0.2"

**Comment by ciniml** [comment]
エラーメッセージに書いてある通り、`authors` の内容に `\c` という無効なエスケープシーケンスがが含まれているのが問題ですね。 `\` を入力したいのであれば `\\` のようにエスケープが必要です。

**Comment by Akud4m4** [comment]
ありがとうございます。無事出来ました。
