### ISSUE TITLE
P.227 s/OneSho/OneShot/

### ISSUE THREAD

**Issue by sago35** [tomoyuki-nakabayashi/Embedded-Rust-from-Basics#5]
P.227 の `ADC 入力を 1 回取得する` の部分のタイトルが `OneSho` になっています。
`OneShot` が正しいかと思います。

**Comment by tomoyuki-nakabayashi** [comment]
ご報告ありがとうございます。
正誤を作成し記載しました。

https://github.com/tomoyuki-nakabayashi/Embedded-Rust-from-Basics/blob/main/correct.md
